resources:
  - name: docker-repo
    type: git
    source:
      uri: {{git_repo_url}}
      branch: master
      private_key: {{git_private_key}}
      username: {{github_user}}

  - name: docker-image
    type: docker-image
    source:
      repository: {{container_fullname}}
      email: {{docker_mail}}
      username: {{docker_user}}
      password: {{docker_password}}
      cache: true

  - name: resource-version
    type: semver
    source:
      driver: git
      initial_version: 0.0.1
      uri: {{git_repo_url}}
      branch: version
      file: version
      private_key: {{git_private_key}}
      username: {{github_user}}

  - name: github-release
    type: github-release
    source:
      user: {{github_user}}
      repository: {{container_name}}
      access_token: {{github_token}}

jobs:
  - name: docker-nodered-release
    serial: true
    plan:
      - get: docker-repo
        trigger: true
      - put: resource-version
        params:
          bump: patch
      - put: docker-image
        params:
          build: docker-repo
          tag: resource-version/version
          tag_as_latest: true
      - put: resource-version
        params:
          file: resource-version/version
      - put: github-release
        params:
          name: resource-version/version
          tag: resource-version/version